import Head from "next/head";
import { NavBar } from "./index";
import { useState } from "react";

type Props = {
  children?: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Pablo air lines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      {children}
    </>
  );
};

export default Layout;
